kind: Service
apiVersion: v1
metadata:
  name: greeting-processor
spec:
  selector:
    app: greeting-processor
  ports:
    - port: 8080
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: greeting-processor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeting-processor
    spec:
      containers:
      - name: greeting-processor
        image: sebastian-daschner.com:1000/greeting-processor:1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /greeting-processor/resources/health-check
            port: 8080
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
