kind: Service
apiVersion: v1
metadata:
  name: greeting-processor
spec:
  selector:
    app: greeting-processor
  ports:
    - port: 8080
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: greeting-processor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeting-processor
    spec:
      containers:
      - name: coffee-shop-processor
        image: rodolpheche/wiremock:2.6.0
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
